//
//  GOOGLEDistanceController.h
//
//  File generated by Magnet rest2mobile 1.0 - Sep 24, 2014 4:27:10 PM
//  @See Also: http://developer.magnet.com
//
#import <Rest2Mobile/Rest2Mobile.h>
@class GOOGLEDistanceResult;

@protocol GOOGLEDistanceControllerProtocol <NSObject>

@optional

/**
 Generated from URL GET http://maps.googleapis.com/maps/api/distancematrix/json?origins=435+Tasso+Street+Palo+Alto+CA&destinations=Embarcadero+Street+San+Francisco+CA&sensor=false&mode=driving&language=en&units=imperial
 GET maps/api/distancematrix/json
 @param origins style:QUERY
 @param destinations style:QUERY
 @param sensor style:QUERY
 @param mode style:QUERY
 @param language style:QUERY
 @param units style:QUERY
 @param success The block to be executed on the completion of a successful request. This block has no return value and takes one argument: the object/primitive constructed from the response data of the request.
 @param failure The block to be executed on the completion of an unsuccessful request. This block has no return value and takes one argument: the error that occurred during the request.
 @return A 'MMCall' object.
 */
- (MMCall *)getDistance:(NSString *)origins
           destinations:(NSString *)destinations
                 sensor:(NSString *)sensor
                   mode:(NSString *)mode
               language:(NSString *)language
                  units:(NSString *)units
                success:(void (^)(GOOGLEDistanceResult *response))success
                failure:(void (^)(NSError *error))failure;

@end

@interface GOOGLEDistanceController : MMController<GOOGLEDistanceControllerProtocol>

@end
