//
//  GOOGLEDistanceController.m
//
//  File generated by Magnet rest2mobile 1.0 - Sep 24, 2014 4:27:11 PM
//  @See Also: http://developer.magnet.com
//
#import "GOOGLEDistanceController.h"

@implementation GOOGLEDistanceController

+ (NSDictionary *)metaData {

    NSMutableDictionary *controllerMetaData = [NSMutableDictionary dictionary];

    MMControllerMethod *method;
    //controller schema for interface GOOGLEDistanceController

    //controller schema for controller method getDistance
    method = [MMControllerMethod new];
    method.name = @"getDistance";
    method.path = @"maps/api/distancematrix/json";
    method.baseURL = [NSURL URLWithString:@"http://maps.googleapis.com"];
    method.method = @"GET";
    method.produces = [NSSet setWithObjects:@"application/json", nil];

    NSMutableArray *gOOGLEDistanceControllerGetDistanceParams = [NSMutableArray new];
    MMControllerParam *gOOGLEDistanceControllerGetDistanceOrigins = [MMControllerParam new];
    gOOGLEDistanceControllerGetDistanceOrigins.name = @"origins";
    gOOGLEDistanceControllerGetDistanceOrigins.style = @"QUERY";
    gOOGLEDistanceControllerGetDistanceOrigins.type = @"NSString *";
    gOOGLEDistanceControllerGetDistanceOrigins.optional = @YES;
    [gOOGLEDistanceControllerGetDistanceParams addObject:gOOGLEDistanceControllerGetDistanceOrigins];

    MMControllerParam *gOOGLEDistanceControllerGetDistanceDestinations = [MMControllerParam new];
    gOOGLEDistanceControllerGetDistanceDestinations.name = @"destinations";
    gOOGLEDistanceControllerGetDistanceDestinations.style = @"QUERY";
    gOOGLEDistanceControllerGetDistanceDestinations.type = @"NSString *";
    gOOGLEDistanceControllerGetDistanceDestinations.optional = @YES;
    [gOOGLEDistanceControllerGetDistanceParams addObject:gOOGLEDistanceControllerGetDistanceDestinations];

    MMControllerParam *gOOGLEDistanceControllerGetDistanceSensor = [MMControllerParam new];
    gOOGLEDistanceControllerGetDistanceSensor.name = @"sensor";
    gOOGLEDistanceControllerGetDistanceSensor.style = @"QUERY";
    gOOGLEDistanceControllerGetDistanceSensor.type = @"NSString *";
    gOOGLEDistanceControllerGetDistanceSensor.optional = @YES;
    [gOOGLEDistanceControllerGetDistanceParams addObject:gOOGLEDistanceControllerGetDistanceSensor];

    MMControllerParam *gOOGLEDistanceControllerGetDistanceMode = [MMControllerParam new];
    gOOGLEDistanceControllerGetDistanceMode.name = @"mode";
    gOOGLEDistanceControllerGetDistanceMode.style = @"QUERY";
    gOOGLEDistanceControllerGetDistanceMode.type = @"NSString *";
    gOOGLEDistanceControllerGetDistanceMode.optional = @YES;
    [gOOGLEDistanceControllerGetDistanceParams addObject:gOOGLEDistanceControllerGetDistanceMode];

    MMControllerParam *gOOGLEDistanceControllerGetDistanceLanguage = [MMControllerParam new];
    gOOGLEDistanceControllerGetDistanceLanguage.name = @"language";
    gOOGLEDistanceControllerGetDistanceLanguage.style = @"QUERY";
    gOOGLEDistanceControllerGetDistanceLanguage.type = @"NSString *";
    gOOGLEDistanceControllerGetDistanceLanguage.optional = @YES;
    [gOOGLEDistanceControllerGetDistanceParams addObject:gOOGLEDistanceControllerGetDistanceLanguage];

    MMControllerParam *gOOGLEDistanceControllerGetDistanceUnits = [MMControllerParam new];
    gOOGLEDistanceControllerGetDistanceUnits.name = @"units";
    gOOGLEDistanceControllerGetDistanceUnits.style = @"QUERY";
    gOOGLEDistanceControllerGetDistanceUnits.type = @"NSString *";
    gOOGLEDistanceControllerGetDistanceUnits.optional = @YES;
    [gOOGLEDistanceControllerGetDistanceParams addObject:gOOGLEDistanceControllerGetDistanceUnits];

    method.parameters = [gOOGLEDistanceControllerGetDistanceParams copy];
    method.returnType = @"_bean:GOOGLEDistanceResult";
    [controllerMetaData setObject:method forKey:@"GOOGLEDistanceController:getDistance"];


    return [controllerMetaData copy];
}

@end
