source 'https://github.com/CocoaPods/Specs'

xcodeproj 'Rest2Mobile Tests'
workspace '../Rest2Mobile'
inhibit_all_warnings!

def import_pods
  pod 'Kiwi', '~> 2.3'
  pod 'Rest2Mobile', :path => '../'
end

target :ios do
  platform :ios, '7.0'
  link_with 'iOS Tests'
  import_pods
end
