/*
 * Copyright (c) 2014 Magnet Systems, Inc.
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License. You
 * may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

#import <Foundation/Foundation.h>

/**
 `MMController` represents a collection of remote API services which can be invoked over REST.
 Each method in the class represents a specific endpoint like GET /users that is accessible over REST.
 
 ## Subclassing Notes
 
 Currently, `MMController` subclasses are auto-generated by the rest2mobile plugin for Xcode found here: https://github.com/magnetsystems/r2m-plugin-ios
 Subclasses can also auto-generated by the rest2mobile Command-line Tool found here: https://github.com/magnetsystems/r2m-cli
 
 ## Methods to Override
 
 Subclasses should override `metaData`, which returns a `NSDictionary` of `MMControllerMethod` objects.
 */

@interface MMController : NSObject

/**
 Returns a collection of `MMControllerMethod` objects.
 Each object contains the metadata for a specific endpoint accessible over REST.
 
 @return A collection of `MMControllerMethod` objects.
 */
+ (NSDictionary *)metaData;

@end

///----------------
/// @name Constants
///----------------

/**
## Error Domains

The following error domain is predefined.

- `NSString * const MMControllerErrorDomain`

### Constants

`MMControllerErrorDomain`
MMControllerErrorDomain errors. For REST controllers, error codes for `MMControllerErrorDomain` correspond to codes in `NSURLErrorDomain`.
*/
extern NSString * const MMControllerErrorDomain;

/**
## User info dictionary keys

These keys may exist in the user info dictionary, in addition to those defined for NSError.

- `NSString * const MMControllerErrorDomainFailingResponseErrorKey`
- `NSString * const MMControllerErrorDomainFailingResponseDataErrorKey`

### Constants

`MMControllerErrorDomainFailingResponseErrorKey`
The corresponding value is an `NSURLResponse` containing the response of the operation associated with an error. This key is only present in the `MMControllerErrorDomain`.

`MMControllerErrorDomainFailingResponseDataErrorKey`
The corresponding value is an `NSData` containing the original data of the operation associated with an error. This key is only present in the `MMControllerErrorDomain`.
*/
extern NSString * const MMControllerErrorDomainFailingResponseErrorKey;

extern NSString * const MMControllerErrorDomainFailingResponseDataErrorKey;