//
//  GOOGLEDuration.h
//
//  File generated by Magnet rest2mobile 1.0 - Sep 24, 2014 4:27:10 PM
//  @See Also: http://developer.magnet.com
//
/** Generated from json example
{
  "value" : 2727,
  "text" : "45 mins"
}

*/

#import <Rest2Mobile/Rest2Mobile.h>


@interface GOOGLEDuration : MMResourceNode <NSCoding>

//field declarations

@property (nonatomic, copy) NSString *text;


@property (nonatomic, assign) int value;



@end
