//
//  GOOGLERow.h
//
//  File generated by Magnet rest2mobile 1.0 - Sep 24, 2014 4:27:10 PM
//  @See Also: http://developer.magnet.com
//
/** Generated from json example
{
  "elements" : [ {
    "status" : "OK",
    "distance" : {
      "value" : 55389,
      "text" : "34.4 mi"
    },
    "duration" : {
      "value" : 2727,
      "text" : "45 mins"
    }
  } ]
}

*/

#import <Rest2Mobile/Rest2Mobile.h>


@interface GOOGLERow : MMResourceNode <NSCoding>

//field declarations

@property (nonatomic, copy) NSArray *elements;



@end
