//
//  GOOGLEDistanceResult.h
//
//  File generated by Magnet rest2mobile 1.0 - Sep 24, 2014 4:27:10 PM
//  @See Also: http://developer.magnet.com
//
/** Generated from json example
{
  "status" : "OK",
  "destination_addresses" : [ "Embarcadero North Street, San Francisco, CA, USA" ],
  "origin_addresses" : [ "435 Tasso Street, Palo Alto, CA 94301, USA" ],
  "rows" : [ {
    "elements" : [ {
      "status" : "OK",
      "distance" : {
        "value" : 55389,
        "text" : "34.4 mi"
      },
      "duration" : {
        "value" : 2727,
        "text" : "45 mins"
      }
    } ]
  } ]
}

*/

#import <Rest2Mobile/Rest2Mobile.h>


@interface GOOGLEDistanceResult : MMResourceNode <NSCoding>

//field declarations

@property (nonatomic, copy) NSArray *destination_addresses;


@property (nonatomic, copy) NSArray *origin_addresses;


@property (nonatomic, copy) NSArray *rows;


@property (nonatomic, copy) NSString *status;



@end
