//
//  GOOGLEDistance.h
//
//  File generated by Magnet rest2mobile 1.0 - Sep 24, 2014 4:27:10 PM
//  @See Also: http://developer.magnet.com
//
/** Generated from json example
{
  "value" : 55389,
  "text" : "34.4 mi"
}

*/

#import <Rest2Mobile/Rest2Mobile.h>


@interface GOOGLEDistance : MMResourceNode <NSCoding>

//field declarations

@property (nonatomic, copy) NSString *text;


@property (nonatomic, assign) int value;



@end
